smart-on-fhir/health-cards-dev-tools

README.md
src/fhirBundle.ts
src/shc-validator.ts
tests/cli.test.ts

Added `--fhirout` option to save the extracted FHIR bundle.

Added option to log extracted FHIR bundle

---

package-lock.json
package.json
src/check-for-update.ts
src/shc-validator.ts

Uses semver package instead of custom code; deletes some code.

Simplified version update check.

---

.github/workflows/node.js.yml

Adds Windows and macOS to the CI OS matrix.

Added matrix OS to github action

---

src/fhirBundle.ts
src/jws-payload.ts

Added JWS payload debug logging, harmonized all such logging to debug level (vs. info).

Added JWS payload debug log

---

src/error.ts
src/jws-payload.ts
testdata/test-example-00-b-jws-payload-expanded-nbf_miliseconds.json
testdata/test-example-00-b-jws-payload-expanded-nbf_not_yet_valid.json
tests/card.test.ts

Warns if health card is "not yet valid", and reports an error if `nbf` is encoded in miliseconds. Fixes issue #46.

Test health card issuance date (nbf)

---

package-lock.json
package.json

Bumped pre-release version to `-2`, to notify users for recent updates.

Bumped version to v0.4.5-2

---

README.md
src/error.ts
src/shc-validator.ts
tests/cli.test.ts

Added *-wildcard error exclusion, and added some key errors exclusions. Fixes #74. Fixes #35.

Added *-wildcard and key error exclusions

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Added CHANGELOG.md file
- Bumped version to v0.4.5-3
- Ran npm update

Bumped version to v0.4.5-3.

---

src/jws-compact.ts

Fix CORS example request.

---

CHANGELOG.md
package-lock.json
package.json

- Updated SDK version
- npm update

Bumped version to 1.0.0-1

---

src/api.ts
src/fhirBundle.ts
src/schema.ts
src/shc-validator.ts
src/validate.ts

- add ability to select profile using the api interface

Add profiles to api

---

src/image.ts

Log qr segments type and content, in debug mode.[](url)

Log qr segments type and content, in debug mode.

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Bumped version to 1.0.0-2
- Ran npm update

Bumped version to v1.0.0-2

---

CHANGELOG.md
package-lock.json
package.json
src/logger.ts

- Bumped version to 1.0.0-3 (after node 16 support, and test files update)
- Ran npm update

Bumped version to 1.0.0-3

---

src/api.ts
src/error.ts
src/fhirBundle.ts
src/healthCard.ts
src/image.ts
src/jws-compact.ts
src/jws-payload.ts
src/qr.ts
src/shc-validator.ts
src/shcKeyValidator.ts
src/validate.ts
tests/card.test.ts
tests/keys.test.ts

- Validation calls no longer return decoded object
- Validation calls now return just the Log
Fixes #100.

Remove return objects from validation calls.

---

src/jws-compact.ts
src/jws-payload.ts
src/schema.ts
src/utils.ts

- Fixed issue where missing jws-payload fields crashed validation
- Fixed some validation checks to use the optional chaining operator ?.
- Fixed typo on an error message

Fix validation crashes

---

src/fhirBundle.ts
src/jws-payload.ts
testdata/test-example-00-b-jws-payload-expanded-missing-covid-vc-type.json
testdata/test-example-00-b-jws-payload-expanded-missing-imm-vc-type.json
testdata/test-example-00-b-jws-payload-expanded-missing-shc-vc-type.json
tests/card.test.ts

Check for expected covid/immunization health cards VC types. Added tests. Addresses part of issue #116; labs check are missing.

Check for expected health cards VC types.

---

CHANGELOG.md
package-lock.json
package.json

Bumped version to 1.0.0-4, ran npm update.

Bumped version to 1.0.0-4

---

CHANGELOG.md
README.md
package-lock.json
package.json

Bumped version to v1.0.1-0

---

README.md

Added security note to README.md.

---

README.md
SUPPORT.md
package-lock.json
package.json
src/check-for-update.ts
src/issuerDirectory.ts
src/shc-validator.ts
tests/api.test.ts
tests/card.test.ts

Renamed project to health-cards-dev-tools

Renamed project to health-cards-dev-tools

---

CHANGELOG.md
README.md
SECURITY.md
package-lock.json
package.json
src/check-for-update.ts
src/jws-compact.ts

Bumped version to 1.0.2-0. Ran `npm audit fix` and `npm update`.

Bumped version to 1.0.2-0

---

src/check-for-update.ts

Updated the path used to lookup the current version on github

update path for version lookup

---

README.md

Added github install from #153, cleaned up text using suggestions from #141.

Updated README, added npm install option.

---

src/fhirBundle.ts
src/jws-payload.ts

Accept all CVX covid codes by default.

Added more CVX covid codes

---

src/fhirBundle.ts
src/fhirHealthCard.ts
src/healthCard.ts
src/jws-compact.ts
src/jws-payload.ts
src/qr.ts
tests/api.test.ts
tests/card.test.ts

- Change white-space warnings to errors
- Update white-space tests to check for errors instead of warning

Update whitespaces warnings to errors

---

CHANGELOG.md
package-lock.json
package.json

Updated package to v1.1.0-0. From CHANGELOG:
- Followed spec version change to v1.1.0
- Promoted extra white spaces warnings to errors
- Added more covid CVX codes
- Added support for direct npm install
- Misc fixes and README.md improvment

Updated package to v1.1.0-0.

---

CHANGELOG.md
package-lock.json
package.json
schema/smart-health-card-vc-schema.json
src/error.ts
src/jws-payload.ts
src/types.ts
testdata/test-example-00-b-jws-payload-expanded-exp_milliseconds.json
testdata/test-example-00-b-jws-payload-expanded-expired.json
testdata/test-example-00-b-jws-payload-expanded-pre-expired.json
tests/card.test.ts

* Checks optional `exp` date
* Adds unit tests
* Bumps dev tools version

Added support for spec v1.2.1 (adding SHC revocation)

---

CHANGELOG.md
README.md
package-lock.json
package.json

* Add HL7 FHIR validator support
* Dependecies update

Updated package to v1.2.1-1

---

src/crl-validator.ts
testdata/badcrl/non-base64url-rid/.well-known/crl/hrvC0uzB16UXK83BnPo7Glg685b1D6iYOyJd5hpRaAA.json
tests/card.test.ts

- add check for duplicate rids in a crl
- add test

Add check for duplicate rids in crl; add test;

---

CHANGELOG.md
README.md
package-lock.json
package.json

Change log v1.2.1-2
- Check for duplicated RID in revocation lists
- Check JWK curve
- Dependencies update

Update to v1.2.1-2

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/api.ts
src/jws-compact.ts
src/options.ts
src/shc-validator.ts
src/shcKeyValidator.ts
src/validate.ts
tests/api.test.ts
tests/card.test.ts
tests/cli.test.ts
tests/keys.test.ts

Added validation time option for SHC and X.509 certs, allowing validation of now expired certs by valid when SHC were issued. Fixes #207.

Added validation time option

---

CHANGELOG.md
README.md
package-lock.json
package.json

* Added validation time option for SHC and X.509 certs
* Updated CVX Covid19 codes
* Dependencies update

Updated to v1.2.1-3

---

CHANGELOG.md
README.md
package-lock.json
package.json

Updated devtool version after spec version update.

Updated devtools to v1.2.2-0
