smart-on-fhir/health-cards-dev-tools

src/error.ts
src/shcKeyValidator.ts
src/utils.ts
tests/keys.test.ts

Adjust tests expected result when OpenSSL is not available (to validate JWK's x5c cert chains)

Handle openssl not present

---

tests/card.test.ts
tests/cli.test.ts
tests/keys.test.ts

Don't expect x5c-related errors if openssl is not available

Adjust expected test behavior if openssl is not present

---

src/check-for-update.ts
src/shc-validator.ts

Tool now checks and warns if there is a newer SDK or spec version.
I debated printing these messages in the output logs, but opted for the console.

Check for SDK or spec update.

---

README.md
src/shcKeyValidator.ts
src/utils.ts

Stop gap fix to issue #47 (and potentially #38) to make sure openssl 1.1.1 is installed before validating x5c chains (until the code logic can workaround older/forked versions of openssl.

Fix failing openssl

---

src/jws-compact.ts
src/shc-validator.ts
src/shcKeyValidator.ts
src/validate.ts
tests/keys.test.ts

Skip issuer JWK set download if provided on the command-line, plus other download clean-ups (timeout, split download/parsing errors). Fixes #53.

Skip JWK set download if provided on command line

---

src/schema.ts

Fixed condition where using invalid property in fhir resource caused an error in validation.
Enabled the 'allErrors' property in AJV to display multiple schema issues to the user instead of just the first issue.
Fixes #67.

break out of loop when property in unknown; enable 'allErrors' in ajv;

---

README.md
package.json

I added a `prepare` script to `package.json` to support `npm install microsoft/health-cards-validation-SDK`, and documented how this option can be used in the README.

Support "npm install" from GitHub

---

package-lock.json
package.json
src/shcKeyValidator.ts
src/utils.ts

Extract issuer cert fields using a new npm package instead of relying on openssl v1.1.1. Should allow us to run x5c validation on systems with openssl v1.0.2, and hopefully libressl (some macs). Fixes #47.
TODO:

Extend x5c validation using openssl 1.0.2 and libressl

---

src/image.ts
tests/card.test.ts

QR code versions higher than 22 should result in an error (vs. warning). Fix #94.

Return error for QR code > v22

---

schema/immunization-dm.json
schema/patient-dm.json
src/fhirBundle.ts
src/schema.ts
src/utils.ts
testdata/test-example-00-a-fhirBundle-empty-values.json
tests/card.test.ts

- Log schema error whenever FHIR element is {}, [], ""
- Updated usa dm schema files as the source schema has been updated.
- Added card test with empty elements
closes #90

Disallow empty fhir elements

---

src/fhirBundle.ts
src/schema.ts

- simplified ajv's schema errors to a  more understandable form
- added some additional fhir pre-schema checks to prevent sending unknown resources to the validator.

Simplified schema errors

---

src/jws-compact.ts

From https://spec.smarthealth.cards/#determining-keys-associated-with-an-issuer:
> Issuers SHALL publish their public keys as JSON Web Key Sets (see RFC7517), available at <<iss value from JWS>> + /.well-known/jwks.json, with Cross-Origin Resource Sharing (CORS) enabled.

Error if CORS is not enabled

---

src/jws-payload.ts
testdata/test-example-00-b-jws-payload-expanded-optional-vc-type.json
testdata/test-example-00-b-jws-payload-expanded-unknown-vc-types.json
tests/card.test.ts

- warns if 'verifiableCredential' vc type is used
- warns if unknown vc type is used (see: https://spec.smarthealth.cards/vocabulary/)
Closes #134

Add warning for optional/unknown vc types

---

README.md
src/fhirBundle.ts

Removed cvx code not currectly approved in the US, from the `usa-covid19-immunization` profile.

Removed non-US approved vaccines from the US profile

---

.npmignore

.npmignore removes a copy of package.json from the /js folder
/js/src/shc-validator.js makes a reference to this file and will error when being called after an npm install from github
Added an exception to .npmignore to preserve that file in the /js directory.

leave package.json in js folder for npm install

---

package-lock.json
package.json
src/shc-validator.ts

- Adds `#!/usr/bin/env node` header to allow direct node execution of `shc-validator.js`
- Adds `bin` entry to `package.json` so that `sch-validator.js` will appear in `./node_modules/.bin` folder
This combination will allow an npm package to install the tool from github and execute the shc-validator.js command line tool directly in their terminal or through scripting (if `./node_modules/.bin` is part of the users path)

Add bin support

---

src/jws-compact.ts

the pako library sometimes silently fails by returning an undefined value; adding a check to catch this case.

Adds check for undefined return value in pako lib.

---

src/fhirBundle.ts

- The current fhir schema json does not require `Immunization.status`
- https://www.hl7.org/fhir/immunization.html does require `Immunization.status`

Require Immunization.status

---

src/fhirBundle.ts
testdata/test-example-00-a-short-refs.json
testdata/test-example-00-b-jws-payload-expanded-missing-coding.json
tests/card.test.ts

Better enforces references in fhir bundle:
- all `.fullUrl` & `.reference` use the form `resource:#`
- `.fullUrl` must be unique within the bundle
- `.reference` must refer to existing `.fullUrl` within the bundle
- tests updated 
Now will result in warnings when the wrong format and when the `.reference` does not match an existing `Entry.fullUrl`
```
FhirBundle
│
└─ Warning
· fhirBundle.entry[2].resourceImmunization.patient = "Patient/resource:0" (Reference) should be short resource-scheme URIs (e.g., {“patient”: {“reference”: “reference”:0”}})
· fhirBundle.entry[2].resourceImmunization.patient = "Patient/resource:0" (Reference) is not one of the defined .fullUrls [resource:0,resource:1,resource:2]
```
closes #174

Enforce strict reference:# in Entry

---

src/fhirBundle.ts
testdata/test-example-00-a-fhirBundle-occurrence-issues.json
tests/api.test.ts
tests/card.test.ts
tests/cli.test.ts

- require **occurrenceDateTime** || **occurrenceString** in Immunization in accordance with http://hl7.org/fhir/R4/immunization.html
-  (https://www.hl7.org/fhir/fhir.schema.json.zip does not require occurrenceDateTime for some reason)
- require only **occurrenceDateTime** w/ `YYYY-MM-DD` format in **usa-covid19-immunization profile**
- added tests for missing and multiple **occurrenceDateTime** || **occurrenceString**
- cleaned up some error output paths to be consistent with the schema error output

Require Immunization/occurrenceDateTime

---

src/fhirBundle.ts

Imported latest codes from https://www.cdc.gov/vaccines/programs/iis/COVID-19-related-codes.html.
Fixes #211.

Updated cvx covid codes
